name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: DDMMYY-HH:MM
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "actor = ${{ github.actor }}"
      - run: echo "time = ${{ steps.current-time.outputs.time }}"
